### PR TITLE
added Unix-Like OS support

### PR DESCRIPTION
**Pull request by ThomasChen0717**

### CODE REVIEW

**Review by mbucko — APPROVED** [review]

**Comment by mbucko** [comment]
I have merged your changes and also added mine on top. A pretty big change, let me know if everything still works ok on your end

**Comment by ThomasChen0717** [comment]
Everything is working on my end. For my next steps, I will try to implement the Java language support.

**Comment by mbucko** [comment]
Ok, great. I added some more information on how to add a new language to docs/index.md that might be useful to you.

Also, let me know if you'd like me to set up a Discord or a Slack channel for support.

**Comment by ThomasChen0717** [comment]
That’ll be great! Thank you!

Miro Bucko ***@***.***>于2024年2月26日 周一下午2:50写道：

**Comment by mbucko** [comment]
I added a discord link to the REAMDE

**Pull request merged**
